<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Olsson.Get.Tests.IntegrationTests</RootNamespace>
    <AssemblyName>Olsson.Get.Tests.IntegrationTests</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Tests|AnyCPU'">
    <OutputPath>bin\Tests\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>IntegrationTests</AssemblyTitle>
    <Product>IntegrationTests</Product>
    <Copyright>Copyright ©  2017</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\Baseline.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\Baseline.hds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\CPNRD.dis">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\CPNRD.hds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\CPNRD.lpf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\CPNRD.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\CPNRD.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\OlssonPostProcess\MonthlyValues.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\PointsOfInterest.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\SegRchZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\CPNRD_streamflow.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Olsson.GET.Accessors\Accessors.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.DataContracts\DataContracts.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.Shared\Shared.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.Utilities\Utilities.csproj" />
    <ProjectReference Include="..\Olsson.GET.Engines\Engines.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ModflowTestFiles\CentralPlatteNaturalResourceDistrictSample\CPNRD.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\Olsson.GET.Common.Shared\Configs\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Remove="..\Olsson.GET.Common.Shared\Configs\appsecrets.template.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CsvHelper" Version="5.0.0.1" />
    <PackageReference Include="FluentAssertions" Version="5.0.0-beta0003" />
    <PackageReference Include="JustMock" Version="2023.1.117.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.*" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="14.0.314.76" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.3.0" />
  </ItemGroup>
</Project>