<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Olsson.GET.Common.Utilities</RootNamespace>
    <AssemblyName>Olsson.GET.Common.Utilities</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Olsson.GET.Shared.Utilities</AssemblyTitle>
    <Product>Olsson.GET.Shared.Utilities</Product>
    <Copyright>Copyright ©  2017</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Olsson.GET.Common.Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="dbup-sqlserver" Version="5.0.8" />
    <PackageReference Include="log4net">
      <Version>2.0.8</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>