<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Olsson.GET.Common.Shared</RootNamespace>
    <AssemblyName>Olsson.GET.Common.Shared</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Olsson.GET.Common.Shared</AssemblyTitle>
    <Product>Olsson.GET.Common.Shared</Product>
    <Copyright>Copyright ©  2017</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'QA|AnyCPU'">
    <OutputPath>bin\QA\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.VisualStudio.SlowCheetah">
      <Version>3.0.61</Version>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Configs\AppSettings.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TransformOnBuild>true</TransformOnBuild>
      <SubType>Designer</SubType>
      <SubType>Designer</SubType>
    </None>
    <None Update="Configs\AppSettings.QA.config">
      <DependentUpon>AppSettings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
      <SubType>Designer</SubType>
    </None>
    <None Update="Configs\AppSettings.Release.config">
      <DependentUpon>AppSettings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
    </None>
    <None Update="Configs\AppSettings.Tests.config">
      <DependentUpon>AppSettings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
    </None>
    <None Update="Configs\AppSettings.Debug.config">
      <DependentUpon>AppSettings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
    </None>
    <None Update="Configs\AppSettings.Debug.config.template">
      <DependentUpon>AppSettings.config</DependentUpon>
      <IsTransformFile>false</IsTransformFile>
    </None>
    <None Update="Configs\ConnectionStrings.config">
      <TransformOnBuild>true</TransformOnBuild>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </None>
    <None Update="Configs\ConnectionStrings.QA.config">
      <DependentUpon>ConnectionStrings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
      <SubType>Designer</SubType>
    </None>
    <None Update="Configs\ConnectionStrings.Release.config">
      <DependentUpon>ConnectionStrings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
    </None>
    <None Update="Configs\ConnectionStrings.Debug.config">
      <DependentUpon>ConnectionStrings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
    </None>
    <None Update="Configs\ConnectionStrings.Debug.config.template">
      <DependentUpon>ConnectionStrings.config</DependentUpon>
      <IsTransformFile>false</IsTransformFile>
    </None>
    <None Update="Configs\ConnectionStrings.Tests.config">
      <DependentUpon>ConnectionStrings.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
    </None>
    <None Update="Configs\Logger.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TransformOnBuild>true</TransformOnBuild>
      <SubType>Designer</SubType>
    </None>
    <None Update="Configs\Logger.Release.config">
      <DependentUpon>Logger.config</DependentUpon>
      <IsTransformFile>True</IsTransformFile>
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
</Project>