<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Olsson.GET.Clients.Agent</RootNamespace>
    <AssemblyName>Olsson.GET.Clients.Agent</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>false</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'QA|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\QA\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\Olsson.GET.Common.Shared\Configs\AppSettings.config">
      <Link>AppSettings.config</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TransformOnBuild>true</TransformOnBuild>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\AppSettings.QA.config">
      <Link>AppSettings.QA.config</Link>
      <DependentUpon>AppSettings.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
      <SubType>Designer</SubType>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\AppSettings.Release.config">
      <Link>AppSettings.Release.config</Link>
      <DependentUpon>AppSettings.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
      <SubType>Designer</SubType>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\ConnectionStrings.config">
      <Link>ConnectionStrings.config</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TransformOnBuild>true</TransformOnBuild>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\ConnectionStrings.QA.config">
      <Link>ConnectionStrings.QA.config</Link>
      <DependentUpon>ConnectionStrings.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\ConnectionStrings.Release.config">
      <Link>ConnectionStrings.Release.config</Link>
      <DependentUpon>ConnectionStrings.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\Logger.config">
      <Link>Logger.config</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TransformOnBuild>true</TransformOnBuild>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\Logger.Release.config">
      <Link>Logger.Release.config</Link>
      <DependentUpon>Logger.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net">
      <Version>2.0.8</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Olsson.GET.Common.Shared\Shared.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.Utilities\Utilities.csproj" />
    <ProjectReference Include="..\Olsson.GET.Managers\Managers.csproj" />
  </ItemGroup>
</Project>