alter table dbo.Model add ModelEngineTypeID int null constraint FK_Model_ModelEngineType_ModelEngineTypeID foreign key references dbo.ModelEngineType(ModelEngineTypeID)
alter table dbo.Model add ModelGridTypeID int null constraint FK_Model_ModelGridType_ModelGridTypeID foreign key references dbo.ModelGridType(ModelGridTypeID)
GO

update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Central Platte NRD'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Cohyst'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'WID'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Central Platte NRD - 50 Year'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'NCORPE Augmentation Pumping'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Spanish Springs'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'WID Level of GW Development'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'CENEB'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM II'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Abilene'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Abilene Calibrated'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Cheyenne County KS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Simple Cheyenne Cnt'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'MERAS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Columbus'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Ashland'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'NPCM'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Keith Cty'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'Cohyst - Modpath'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'HPAS'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'RRCA - dry'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'RRCA - wet'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'RRCA - normal'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'COHYST - dry'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'COHYST - wet'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'COHYST - normal'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'CENEB - dry'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'CENEB - wet'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'CENEB - normal'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'NCORPE Baseline'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'UNW - wet'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'UNW - dry'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'UNW - normal'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'WWUM - wet'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'WWUM - normal'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'WWUM - dry'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'Blue Basin - wet'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'Blue Basin - normal'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'Blue Basin - dry'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Arbuckle-Simpson'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'NACP'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM III'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'Cheyenne County - MODPATH'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM III Future'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Monett'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Robust Review TPNRD'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'SRV'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'GI Dewatering'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM III Future - huc 8'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM III - WQA'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM II - WQA'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'CENEB - WQA'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'Columbus - MODPATH'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Lower Dakota'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Upper Humboldt'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'LPMT'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Upper Humboldt 100 yr'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'RRBWSD'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'LPMT - Wet'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'LPMT - Dry'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'LPMT - Normal'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'LPMT-LWS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'COHYST LWS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Southwest Georgia'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Blue Basin'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'CENEB LWS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'CENEB LWS 2'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Southwest Georgia 2'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Southwest Georgia 3'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'ELM III - MODPATH'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'RRBWSD - MODPATH'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'NPCM-AEM'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'NCORPE-AEM'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'COHYST NRDs'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Great Basin National Park'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Sargent'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'COHYST Sub-GWMAs'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'URNRD Calibration'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Trinity Hill'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'COHYST mf6'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'COHYST v25'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'COHYST v28'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'COHYST v28b'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'CENEB Calibration'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM Calibration'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'COHYST Future Climate'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'COHYST mf6 v28b'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'URNRD HOBS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'CENEB-Niobrara Overlap'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'URNRD Future-40'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Baseline Model'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'CENEB-Niobrara Overlap - USGS'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V1 - USGS'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V1 - Flatwater'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 2 where ModelName = 'Monolith'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Lower Humboldt'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Middle Humboldt'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Upper Humboldt 2020'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Lower Humboldt - Monthly'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Lower Humboldt - Capture'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V1 SS - USGS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'URNRD Future-100'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Sustainability'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'RRBWSD - 5yr'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'BSEACD'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Death Valley'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'URNRD Calibration V2'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V2 - USGS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Sustainability-V2'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Upper Humboldt 2020 - Capture'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Death Valley - Capture'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V3 - Flatwater'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V3 - USGS'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V2.1 - USGS'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Death Valley - Predict'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 2 where ModelName = 'Brady-Maxwell'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 2 where ModelName = 'NPCM - mf6'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 2 where ModelName = 'WID - mf6'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'Deschutes 2008'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'RRCA'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V4 - USGS'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V4 - Flatwater'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V4 Future - Flatwater'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara V4 Future - USGS'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'Niobrara 2015'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'COHYST v29e'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'GMD 1'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'GMD 1 - Future'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'COHYST v29e Future'
update dbo.Model set ModelEngineTypeID = 2, ModelGridTypeID = 1 where ModelName = 'ELM III Current'
update dbo.Model set ModelEngineTypeID = 4, ModelGridTypeID = 1, ModflowExeName = '..\!bin\IWFM2015.0.961\Simulation2015_x64.exe',  ZoneBudgetExeName = '..\Budget\Budget.bat' where ModelName = 'MercedWRM'

-- QA only models
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'ModFlow 6 Structured'
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 2 where ModelName = 'ModFlow 6 Unstructured'
update dbo.Model set ModelEngineTypeID = 1, ModelGridTypeID = 1 where ModelName = 'COHYST MODPATH'

-- Staging only models
update dbo.Model set ModelEngineTypeID = 3, ModelGridTypeID = 1 where ModelName = 'URNRD MF6 Calibration'


alter table dbo.Model alter column ModelEngineTypeID int not null
alter table dbo.Model alter column ModelGridTypeID int not null
