<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Olsson.GET.Tests.ManagerTests</RootNamespace>
    <AssemblyName>Olsson.GET.Tests.ManagerTests</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Tests|AnyCPU'">
    <OutputPath>bin\Tests\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>ManagerTests</AssemblyTitle>
    <Product>ManagerTests</Product>
    <Copyright>Copyright ©  2017</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\Olsson.GET.Common.Shared\Configs\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Remove="..\Olsson.GET.Common.Shared\Configs\appsecrets.template.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Olsson.GET.Accessors\Accessors.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.DataContracts\DataContracts.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.Shared\Shared.csproj" />
    <ProjectReference Include="..\Olsson.GET.Engines\Engines.csproj" />
    <ProjectReference Include="..\Olsson.GET.Managers\Managers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.0.0-beta0003" />
    <PackageReference Include="JustMock" Version="2023.1.117.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.*" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.3.0" />
  </ItemGroup>
</Project>