<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Olsson.GET.Tests.AccessorTests</RootNamespace>
    <AssemblyName>Olsson.GET.Tests.AccessorTests</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <TestProjectType>UnitTest</TestProjectType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Tests|AnyCPU'">
    <OutputPath>bin\Tests\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
    
  <ItemGroup>
    <None Include="..\Olsson.GET.Common.Shared\Configs\Logger.config">
      <Link>Logger.config</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TransformOnBuild>true</TransformOnBuild>
    </None>
    <None Include="..\Olsson.GET.Common.Shared\Configs\Logger.Release.config">
      <Link>Logger.Release.config</Link>
      <DependentUpon>Logger.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Update="ModflowTestFiles\CreateModflowFileAccessor\StructuredModFlow2005\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CreateModflowFileAccessor\StructuredModFlow6\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CreateModflowFileAccessor\StructuredModFlow6\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CreateModflowFileAccessor\UnstructuredModFlow2005\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CreateModflowFileAccessor\UnstructuredModFlow6\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\CreateModflowFileAccessor\UnstructuredModFlow6\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetFriendlyZoneBudgetName\BasicTest\ZoneBudgetNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetPointsOfInterest\BasicTest\PointsOfInterest.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetObservedPointsOfInterest\Differential\Observed.PointsOfInterest.Differential.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetObservedPointsOfInterest\NonDifferential\Observed.PointsOfInterest.NonDifferential.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetObservedZoneBudget\Differential\Observed.ZoneBudget.Differential.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetObservedZoneBudget\NonDifferential\Observed.ZoneBudget.NonDifferential.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetObservedImpactToBaseflow\Differential\Observed.ImpactToBaseflow.Differential.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetObservedImpactToBaseflow\MultiWordDataSeries\Observed.ImpactToBaseflow.NonDifferential.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetObservedImpactToBaseflow\NonDifferential\Observed.ImpactToBaseflow.NonDifferential.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetRunZoneBudgetItems\HasRecords\Scenario.2.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetRunZoneBudgetItems\HasUndefinedValue\Scenario.2.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetRunZoneBudgetItems\NoData\Scenario.2.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetBaselineZoneBudgetItems\HasRecords\BaselineZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetBaselineZoneBudgetItems\HasUndefinedValue\BaselineZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetBaselineZoneBudgetItems\NoData\BaselineZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetZoneBudgetAsrDataNameMap\EmptyZoneSpecificFile\AsrDataNameMap.ZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetZoneBudgetAsrDataNameMap\EmptyZoneSpecificFile\AsrDataNameMap.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetZoneBudgetAsrDataNameMap\HasZoneSpecificData\AsrDataNameMap.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetZoneBudgetAsrDataNameMap\HasZoneSpecificData\AsrDataNameMap.ZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetZoneBudgetAsrDataNameMap\MissingZoneSpecificFile\AsrDataNameMap.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\IsStructuredFile\StructuredModFlow2005\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\IsStructuredFile\StructuredModFlow6\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\IsStructuredFile\StructuredModFlow6\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\IsStructuredFile\UnstructuredModFlow2005\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\IsStructuredFile\UnstructuredModFlow6\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\IsStructuredFile\UnstructuredModFlow6\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetAquiferFlowData\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetAquiferFlowData\flow.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetAquiferFlowData\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetAsrDataNameMap\BasicTest\AsrDataNameMap.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\HasEmptyOptions\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\HasEmptyOptions\test1tr.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\HasEmptyOptions\test1tr.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\HasNoOptions\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\HasNoOptions\test1tr.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\HasNoOptions\test1tr.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\DifferentCasedHeaders\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\DifferentCasedHeaders\test1tr.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\DifferentCasedHeaders\test1tr.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\BasicTest\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\BasicTest\test1tr.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetLocationRates\BasicTest\test1tr.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetMapData\Baseline.hds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetMapData\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetMapData\test1tr.hds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetMapData\test1tr.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    
    <Content Include="..\Olsson.GET.Common.Shared\Configs\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Remove="..\Olsson.GET.Common.Shared\Configs\appsecrets.template.json" />
    
    <Content Include="ModflowTestFiles\ModflowSixStructured\GetAquiferFlowData\Baseline_Reach_Name_Column.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ModflowTestFiles\ModflowSixStructured\GetAquiferFlowData\Baseline_New_Format_02_19_2021.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ModflowTestFiles\ModflowSixStructured\GetRunListFileLines\mfsim.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetNumberOfSegmentReaches\BasicTest\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetNumberOfSegmentReaches\BasicTest\flow.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetNumberOfSegmentReaches\BasicTest\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetNumberOfSegmentReaches\ExtraSpaces\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetNumberOfSegmentReaches\ExtraSpaces\flow.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetNumberOfSegmentReaches\ExtraSpaces\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetSegmentReachZones\BasicTest\SegRchZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\BasicTest\BaselineZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\BasicTest\zbud.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\BasicTest\ZoneBudgetNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\BasicTest\ZoneNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetStressPeriodData\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetStressPeriodData\simulation.tdis">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\GetStressPeriodData\test1tr.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\MultiplePackageNames\zbud.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\MultiplePackageNames\BaselineZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\MultiplePackageNames\ZoneBudgetNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\ZoneBudgetItems\MultiplePackageNames\ZoneNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetAquiferFlowData\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetAquiferFlowData\flow.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetAquiferFlowData\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetAsrDataNameMap\BasicTest\AsrDataNameMap.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\HasNoOptions\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\HasNoOptions\flow.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\HasNoOptions\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\HasEmptyOptions\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\HasEmptyOptions\flow.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\HasEmptyOptions\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\DifferentCasedHeaders\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\DifferentCasedHeaders\flow.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\DifferentCasedHeaders\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\BasicTest\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\UpdateLocationRates\BasicTest\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\UpdateLocationRates\BasicTest\test1tr.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixStructured\UpdateLocationRates\BasicTest\test1tr.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\BasicTest\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetMapData\Baseline.hds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetMapData\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetMapData\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetNumberOfSegmentReaches\BasicTest\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetNumberOfSegmentReaches\BasicTest\flow.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetNumberOfSegmentReaches\BasicTest\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetNumberOfSegmentReaches\ExtraSpaces\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetNumberOfSegmentReaches\ExtraSpaces\flow.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetNumberOfSegmentReaches\ExtraSpaces\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetStressPeriodData\flow.tdis">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetStressPeriodData\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetStressPeriodData\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\GetLocationRates\BasicTest\flow.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\UpdateLocationRates\BasicTest\flow.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\BasicTest\zbud.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\UpdateLocationRates\BasicTest\flow.wel">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\UpdateLocationRates\BasicTest\mfsim.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\BasicTest\BaselineZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\BasicTest\ZoneBudgetNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\BasicTest\ZoneNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\MultiplePackageNames\zbud.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\MultiplePackageNames\BaselineZoneBudget.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\MultiplePackageNames\ZoneBudgetNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\ModflowSixUnstructured\ZoneBudgetItems\MultiplePackageNames\ZoneNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Modpath\COHYST.mpsim">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Modpath\COHYST2010_28b_14_28.timeseries7">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetBaselineData\BasicTest\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\FindWellLocations\NoPumpingWellData\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\FindWellLocations\IncludesMultiplePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\FindWellLocations\IncludesMultiplePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\FindWellLocations\IncludesSinglePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\FindWellLocations\IncludesSinglePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetBaselineData\NoFile\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationPositionMap\IncludesMultiplePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationPositionMap\IncludesMultiplePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationPositionMap\IncludesSinglePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationPositionMap\IncludesSinglePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\ClnColumnTrue\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\ClnColumnTrue\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\HasMultipleValues\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\HasMultipleValues\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\ClnColumnFalse\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\ClnColumnFalse\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\HasSingleValue\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationProportions\HasSingleValue\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationRates\MultipleWellGroups\Name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationRates\MultipleWellGroups\Well.WEL">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationZones\InputLocationZonesCsv\InputLocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationZones\MultipleZonesFound\LocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationZones\SingleZoneFound\LocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationZones\NodeNotInFile\LocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetOutputData\NoFile\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetOutputLocationZones\Valid\OutputLocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetStressPeriodData\NoFile\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\ReduceMapCells\HugeTest\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetBaselineData\BasicTest\Baseline.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetBaselineData\BasicTest\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetFriendlyZoneName\BasicTest\ZoneNames.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\FindWellLocations\NoPumpingWellData\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\FindWellLocations\IncludesMultiplePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\FindWellLocations\IncludesMultiplePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\FindWellLocations\IncludesSinglePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\FindWellLocations\IncludesSinglePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetBaselineData\NoFile\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationPositionMap\IncludesMultiplePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationPositionMap\IncludesSinglePumpingWellDataWithoutProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationPositionMap\IncludesMultiplePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationPositionMap\IncludesSinglePumpingWellDataWithProportion\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\ClnColumnTrue\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\ClnColumnTrue\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\HasMultipleValues\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\HasMultipleValues\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\ClnColumnFalse\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\ClnColumnFalse\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\HasSingleValue\LocationFlowProportions.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationProportions\HasSingleValue\name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationRates\BasicTest\Name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetLocationRates\BasicTest\Well.WEL">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetOutputData\BasicTest\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationRates\MultipleWellGroups\Name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationRates\MultipleWellGroups\Well.WEL">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationZones\InputLocationZonesCsv\InputLocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationZones\MultipleZonesFound\LocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationZones\NodeNotInFile\LocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationZones\SingleZoneFound\LocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetOutputData\BasicTest\BasicTest.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetOutputData\BasicTest\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetOutputData\NoFile\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetOutputLocationZones\Valid\OutputLocationZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetStressPeriodData\NoFile\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetStressPeriodData\BasicTest\test.dis">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetStressPeriodData\BasicTest\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetStressPeriodData\NotEnoughData\test.dis">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetStressPeriodData\NotEnoughData\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\UpdateLocationRates\BasicTest\Name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\UpdateLocationRates\BasicTest\Well.WEL">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\UpdateLocationRates\BasicTest\Name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\UpdateLocationRates\BasicTest\Well.WEL">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationRates\BasicTest\Name.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationRates\BasicTest\Well.WEL">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetNumberOfSegmentReaches\BasicTest\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetNumberOfSegmentReaches\BasicTest\test.sfr">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetBaselineData\BasicTest\Baseline.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetOutputData\BasicTest\BasicTest.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetStressPeriodData\NotEnoughData\test.dis">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetStressPeriodData\NotEnoughData\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetStressPeriodData\BasicTest\test.dis">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Structured\GetStressPeriodData\BasicTest\test.nam">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\GetSegmentReachZones\BasicTest\SegRchZones.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Olsson.GET.Accessors\Accessors.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.DataContracts\DataContracts.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ModflowTestFiles\Structured\GetLocationPositionMap\BasicTest\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ModflowTestFiles\Unstructured\GetLocationPositionMap\BasicTest\LocationMapCoordinates.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ModflowTestFiles\GetBaselineZoneBudgetItems\NoFile\" />
    <Folder Include="ModflowTestFiles\GetFriendlyZoneBudgetName\DoesntExist\" />
    <Folder Include="ModflowTestFiles\GetFriendlyZoneName\DoesntExist\" />
    <Folder Include="ModflowTestFiles\GetObservedImpactToBaseflow\DoesntExist\" />
    <Folder Include="ModflowTestFiles\GetObservedPointsOfInterest\DoesntExist\" />
    <Folder Include="ModflowTestFiles\GetObservedZoneBudget\DoesntExist\" />
    <Folder Include="ModflowTestFiles\GetPointsOfInterest\DoesntExist\" />
    <Folder Include="ModflowTestFiles\GetRunZoneBudgetItems\NoFile\" />
    <Folder Include="ModflowTestFiles\GetSegmentReachZones\DoesntExist\" />
    <Folder Include="ModflowTestFiles\GetZoneBudgetAsrDataNameMap\NoAsrDataAtAll\" />
    <Folder Include="ModflowTestFiles\ModflowSixStructured\GetSegmentReachZones\DoesntExist\" />
    <Folder Include="ModflowTestFiles\Structured\GetLocationZones\FileNotFound\" />
    <Folder Include="ModflowTestFiles\Unstructured\GetLocationZones\FileNotFound\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ModflowTestFiles\ModflowSixStructured\GetAquiferFlowData\Baseline.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ModflowTestFiles\ModflowSixStructured\GetAquiferFlowData\test1tr.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ModflowTestFiles\ModflowSixUnstructured\GetAquiferFlowData\Baseline.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ModflowTestFiles\ModflowSixUnstructured\GetAquiferFlowData\flow.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ModflowTestFiles\ModflowSixUnstructured\GetRunListFileLines\mfsim.lst">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\readme.htm" />
    <Content Include="SqlServerTypes\x64\msvcr120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x64\SqlServerSpatial140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x86\msvcr120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x86\SqlServerSpatial140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.0.0-beta0003" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.*" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.3.0" />
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>
  <ItemDefinitionGroup>
    <_NoneWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </_NoneWithTargetPath>
    <ContentWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </ContentWithTargetPath>
  </ItemDefinitionGroup>
  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>
</Project>