<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Olsson.GET.Databases.Primary</RootNamespace>
    <AssemblyName>Olsson.GET.Databases.Primary</AssemblyName>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Olsson.GET.Databases.Primary</AssemblyTitle>
    <Product>Olsson.GET.Databases.Primary</Product>
    <Copyright>Copyright ©  2017</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Tests|AnyCPU'">
    <OutputPath>bin\Tests\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <None Update="App.Release.config">
      <DependentUpon>App.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Olsson.GET.Common.Shared\Shared.csproj" />
    <ProjectReference Include="..\Olsson.GET.Common.Utilities\Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\001\001.Start.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\001\002.Users.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\001\003.AddPhoneNumberToUsers.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\001\004.Customers.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\002\001.Runs.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\002\002.RunDeleteFlag.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\001.SampleData.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\002.ColumnRequiredFix.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\003.RunFileName.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\005.ModelScenarioNames.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\004.RunDates.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\006.ModelModflowFiles.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\007.ModelModflowInputFiles.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\008.ModelAddAllowablePercentDiscrepancy.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\009.UserEULA.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\010.CohystModel.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\011.ModelFriendlyZoneNames.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\003\012.UpsertModelStoredProcedure.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\001.MapSettings.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\002.ModelLocationMapFileName.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\003.FixModelLocationMapFileNameOnWrongModel.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\004.ModelMapOutputFiles.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Olsson.GET.Common.Shared\Configs\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Remove="..\Olsson.GET.Common.Shared\Configs\appsecrets.template.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\005.ModelMapOutputFiles.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\006.GeometryMathTables.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\008.StructuredModelHeatMaps.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\007.UpdateCpnrdModelLocationMapFile.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\001.InputControls.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\009.CpnrdBoundsUpdate.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\010.SetUserSecurityStamps.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\011.RunCreateMapsFlag.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\004\012.ConventionBasedFileNames.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\002.ClientAdmin.sql" />
    <EmbeddedResource Include="Migrations\005\003.NewWIDmodel.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\004.ModelZones.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\005.ModelName.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\006.UpsertUpdate.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\007.ScenarioSignSwitcher.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\008.TrialModel.sql" />
    <EmbeddedResource Include="Migrations\006\001.ZoneBudget.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\005\009.CPNRD50yr.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\001.ModelInfo.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\004.NewModelSprocs.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\005.ModelDataUpdate.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\007.ncorpe.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\006.NullableRunFileName.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\008.WidCanalNames.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\009.AddScen2COHYST.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\010.COHYSTzoneUpdate.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\011.SpanishSprM.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\012.Add2Scenarios.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\013.FixCohystStressPeriods.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\014.WIDwateruse.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\015.CENEB.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\016.CENEB_adj_irr.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\017.elm_II.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\018.abilene.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\019.AbilenUpdateVars.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\020.Abilene50yr.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\021.CENEBzonebudget.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\022.CheyenneCnt.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\023.UpdateCheyenne.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\024.CheyenneSimple.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\025.AddASRscen.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\026.AddAWellScen.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\027.SwitchAbileneImageNames.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\028.MERAS.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\029.AddCanalScen.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\030.AddCanalScen.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\031.columbus.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\032.Columbusupdates.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\033.Ashland.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\034.NPCM.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\035.KeithCty.sql" />
    <EmbeddedResource Include="Migrations\006\036.UpdateNPCM.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\037.KeithCtyZB.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\006\038.CENEBstartDateTime.sql" />
    <EmbeddedResource Include="Migrations\006\039.ELMstartDateTime.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\001.ModPathConfigs.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\002.SimFile.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\003.ModelScripts.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\004.RunOutput.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\005.HPAS.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\006.RRCAdry.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\007.RRCAwet.sql" />
    <EmbeddedResource Include="Migrations\007\008.RRCAnormal.sql" />
    <EmbeddedResource Include="Migrations\007\009.COHYSTdry.sql" />
    <EmbeddedResource Include="Migrations\007\010.COHYSTwet.sql" />
    <EmbeddedResource Include="Migrations\007\011.COHYSTnormal.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\012.CENEBdry.sql" />
    <EmbeddedResource Include="Migrations\007\013.CENEBwet.sql" />
    <EmbeddedResource Include="Migrations\007\014.CENEBnormal.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\015.NCORPEbl.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\015.UNWwet.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\017.UNWnormal.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\016.UNWdry.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\018.WWUMwet.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\019.WWUMnormal.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\020.WWUMdry.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\021.BBwet.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\022.BBnormal.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\023.BBdry.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\024.ArbuckleSimpson.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\026.NCORPEbl_zb.sql" />
    <EmbeddedResource Include="Migrations\007\025.NCORPE_zb.sql" />
    <EmbeddedResource Include="Migrations\007\027.CENEB_add_lillian.sql" />
    <EmbeddedResource Include="Migrations\007\028.ELM_add_lillian.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\029.NACP.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\030.ELMIII.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\031.ELMIIIremoveZB.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\032.ELMaddZB.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\033.CheyenneMODPATH.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\034.ELMIIIfuture.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\035.Monett.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\036.TPNRDrr.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\037.SRV.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\038.GI.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\039.ELMIIIfutureHUC.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\040.ELMIIIhuc.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\041.ELMIIhuc.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\042.CENEBhuc.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\043.ColumbusMP.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\044.Columbusupdates.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\045.Columbusupdates2.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\046.Columbusupdates3.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\047.LowerDakota.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\048.UpperHumbolt.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\049.LPMT.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\050.updateLPMT.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\051.updateUHM.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\053.100yrUHM.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\054.RRBWSD.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\055.LPMT-wet.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\057.LPMT-normal.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\056.LPMT-dry.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\058.LPMT-lwss.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\059.updateLPMT.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\060.COHYSTlws.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\061.Georgia.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\062.BlueBasin.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\063.updateBlueBasin.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\064.CENEBlws.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\065.CENEBlws2.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\066.updateCOHYST.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\067.Georgia2.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\067.GeorgiaNoQbl.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\007\068.ELMIIImodpath.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\001.ScenarioImage.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\002.ImageUpdates.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\003.ScenarioFiles.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\004.ScenarioFilesConstraint.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\005.RunRestartCount.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\006.GlobalRchAdjust.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\007.NPCMaem.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\008.updateKeithCty.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\009.ELMIIrchAdj.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\010.NCORPEaem.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\011.UpdateGeorgia3.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\012.COHYSTrch.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\013.UpdateNCORPEaem.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\014.AdjQbyZone.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\008\015.KeithAdjQbyZone.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\001.VolumeUnitOnRunsTable.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\006.AddIsDifferentialFlagToRuns.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\002.ActionBuckets.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\003.ActionBucketIsDeleted.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\004.AddBuddyGroups.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\005.ActionBucketsRemoveIsDeleted.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\007.ActionBucketsRemoveFileStorageLocator.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\008.AddDrawdownFileNameToModels.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\009.UpdateStoredProceeduresForDrawdown.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\010.UpdateModelsForModflowSix.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\011.UpdateModelUpsertForModflowSix.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\012.RemoveIsModflowSixColumn.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\013.UpdateUpsertMethods.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\014.FixRetrieveModel.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\015.AddDescriptionToRuns.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\009\016.AddDescriptionToRunBuckets.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\010\001.AddOutputZoneDataToModelsRenameInputZoneToInputZoneDataUpdateUpsertMethods.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\010\002.AddBaseflowTableProcessingConfigurationAndAddToModel.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\010\003.AddBaseflowTableProcessingConfigurationIDToUpsertModelAndRetrieveModel.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\010\004.AddpInsertBaseflowTableProcessingConfiguration.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\010\005.AddCustomTypeForEnteringListOfDatesAndModelStressPeriodCustomStartDatestable.sql" />
    <EmbeddedResource Include="Migrations\010\006.UpdateUpsertModelToIncludeCustomStartDatesForStressPeriods.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\010\007.AddDescriptionAndShowToAllUsersInScenarioListToSecnariosTable.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\011\001.AddDescriptionToModel.sql" />
    <EmbeddedResource Include="Migrations\012\001.Update Length of Scenario Description.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\012\002.Create view to summarize model and scenario count for customer.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\013\001.Create data model for file resources and report templates.sql" />
    <EmbeddedResource Include="Migrations\013\002.Add FileResourceMimeTypes.sql" />
    <EmbeddedResource Include="Migrations\013\003.Add ReportTemplateModels.sql" />
    <EmbeddedResource Include="Migrations\013\004.Add ReportTemplateModelTypes.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\014\002.Add IsAvailableForAllConfigurations to ReportTemplate.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\014\001.Add CanManageReports to User.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\014\003.Add ReportCustomerModelScenario.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\015\002.AddRichTextFieldsToScenarioAndModel.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\015\001.ChangeModelNames.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\001.Create RunStatus table.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\002.Changing existing tables to facilitate generator.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\003.Adding primary key column to view.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\004.Changing Users reference to User.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\005.Removing old tables.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\006.Updating VolumeUnit display name.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\007.Updating stored procedures.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\016\008.Add GETPageType and GETPage to follow PF standard for rich text pages.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\001.Add ExternalMapLayerType and ExternalMapLayer.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\002.Add GET Page for External Map Layer List.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\003.Update Unknown VolumeUnit to be NotApplicable.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\004.Create TimeframeType table and link it to VolumeUnit.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\005.Create MeasurementType table.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\006.Create ExternalMapLayerCustomerModel table, add  IsAvailableForAllConfigurations to ExternalMapLayer.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\007.Add FeatureNameField to ExternalMapLayer.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\017\008.Add TokenProtectedEsriFeatureServer to ExternalMapLayerType and Token to ExternalMapLayer.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\018\001.Remove MapModelArea, InputZoneData and OutputZoneData from Model table into their own tables to speed up application.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\018\002.Correct error in upsert model procedure.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\019\001.Update UserRole and ensure everyone has a role.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\020\001.Add ModelEngine table.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\020\002.Add ModelEnginID to Model table.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\020\003.Collapsing exe names and renaming zonebudgeexename.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\020\004.Moving executables to ModelExecutable table.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\021\001.Remove UpsertModel sproc.sql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="dbup-sqlserver" Version="5.0.8" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>